-- CreateTable
CREATE TABLE "USER" (
    "USEN_ID" SERIAL NOT NULL,
    "USEC_URLPP" VARCHAR(255),
    "USEC_LNAME" VARCHAR(255),
    "USEC_FNAME" VARCHAR(255),
    "USEC_TYPE" VARCHAR(10),
    "USEC_BIO" TEXT,
    "USED_BIRTH" DATE,
    "USEC_TEL" VARCHAR(15),
    "USEC_ADDRESS" TEXT,
    "USEC_MAIL" VARCHAR(255),
    "USEC_PASSWORD" TEXT,
    "USEN_INVITE" INTEGER,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("USEN_ID")
);

-- CreateTable
CREATE TABLE "ACCOMMODATION" (
    "ACCN_ID" SERIAL NOT NULL,
    "ACCC_NAME" VARCHAR(255),
    "ACCC_TYPE" VARCHAR(50),
    "ACCC_DESC" TEXT,
    "ACCC_ADDRESS" TEXT,
    "ACCB_AVAILABLE" BOOLEAN DEFAULT true,
    "USEN_ID" INTEGER,

    CONSTRAINT "ACCOMMODATION_pkey" PRIMARY KEY ("ACCN_ID")
);

-- CreateTable
CREATE TABLE "EVENT" (
    "EVEN_ID" SERIAL NOT NULL,
    "EVEC_LIB" VARCHAR(255),
    "EVED_START" TIMESTAMP(6),
    "EVED_END" TIMESTAMP(6),
    "USEN_ID" INTEGER,
    "ACCN_ID" INTEGER,

    CONSTRAINT "EVENT_pkey" PRIMARY KEY ("EVEN_ID")
);

-- CreateTable
CREATE TABLE "MESSAGE" (
    "MESN_ID" SERIAL NOT NULL,
    "MESN_RECEIVER" INTEGER,
    "MESN_SENDER" INTEGER,
    "MESC_CONTENT" TEXT,
    "MESD_DATE" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "MESB_NEW" BOOLEAN DEFAULT true,

    CONSTRAINT "MESSAGE_pkey" PRIMARY KEY ("MESN_ID")
);

-- CreateTable
CREATE TABLE "LEASE" (
    "LEAN_ID" SERIAL NOT NULL,
    "LEAD_START" DATE,
    "LEAD_END" DATE,
    "LEAN_RENT" DECIMAL(10,2),
    "LEAN_CHARGES" DECIMAL(10,2),
    "LEAD_PAYMENT" DATE,
    "LEAB_ACTIVE" BOOLEAN DEFAULT true,
    "USEN_ID" INTEGER,
    "ACCN_ID" INTEGER,

    CONSTRAINT "LEASE_pkey" PRIMARY KEY ("LEAN_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_USEC_MAIL_key" ON "USER"("USEC_MAIL");

-- AddForeignKey
ALTER TABLE "USER" ADD CONSTRAINT "fk_invite_owner" FOREIGN KEY ("USEN_INVITE") REFERENCES "USER"("USEN_ID") ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ACCOMMODATION" ADD CONSTRAINT "fk_accommodation_user" FOREIGN KEY ("USEN_ID") REFERENCES "USER"("USEN_ID") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "EVENT" ADD CONSTRAINT "fk_event_accommodation" FOREIGN KEY ("ACCN_ID") REFERENCES "ACCOMMODATION"("ACCN_ID") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "EVENT" ADD CONSTRAINT "fk_event_user" FOREIGN KEY ("USEN_ID") REFERENCES "USER"("USEN_ID") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "MESSAGE" ADD CONSTRAINT "fk_message_receiver" FOREIGN KEY ("MESN_RECEIVER") REFERENCES "USER"("USEN_ID") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "MESSAGE" ADD CONSTRAINT "fk_message_sender" FOREIGN KEY ("MESN_SENDER") REFERENCES "USER"("USEN_ID") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "LEASE" ADD CONSTRAINT "fk_lease_accommodation" FOREIGN KEY ("ACCN_ID") REFERENCES "ACCOMMODATION"("ACCN_ID") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "LEASE" ADD CONSTRAINT "fk_lease_user" FOREIGN KEY ("USEN_ID") REFERENCES "USER"("USEN_ID") ON DELETE CASCADE ON UPDATE NO ACTION;
